version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Map container port 3000 to local port 3000
    volumes:
      - .:/app       # Mount the project directory for live changes
      - /app/node_modules  # Prevent overwriting `node_modules` in the container
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--turbopack"]
